### ISSUE TITLE
App\Url::sequence must return a relationship instance.

### ISSUE THREAD

**Issue by vaughany** [highsolutions/eloquent-sequence#1]
Hi there. I have the below model:

```
<?php

namespace App;
use HighSolutions\EloquentSequence\Sequence;
use Illuminate\Database\Eloquent\Model;

class Url extends Model {
    use Sequence;

    public function sequence() {
        return [
            'group' => 'page_id',
            'fieldName' => 'sequence',
        ];
    }
}
```

When I attempt to save a new Url instance (or run `--seed` when refreshing migrations) I get the following error:

```
App\Url::sequence must return a relationship instance.
```

I'm using Laravel 5.5.24.

**Comment by highsolutions** [comment]
Hi @vaughany . I think the problem is that the field has the same name as method. We use `seq` often. Try this.

**Comment by vaughany** [comment]
Thank you. May submit a PR with a warning to this effect.
