### ISSUE TITLE
Is it possible for many to many relation?

### ISSUE THREAD

**Issue by kotenarok** [highsolutions/eloquent-sequence#10]
Is it possible for many to many relation?

**Comment by highsolutions** [comment]
Hi @kotenarok yes, it's possible, but when you want to use many-2-many you need to create a model for this pivot table.

**Comment by highsolutions** [comment]
When you have model Car and Tire then you need to have model CarTires which is based on table car_tire (as normal many-to-many). This prevents in using methods sync etc., but allows for using our package in many-to-many relations.

**Comment by SidharthRaveendran** [comment]
Can you help me out with an example of how it'd be implemented?
