### ISSUE TITLE
Does deletion of a record 

### ISSUE THREAD

**Issue by byanju** [highsolutions/eloquent-sequence#11]
Does deletion of a record with sequence always updates the sequence number of other records within the same group. If yes then is there any way that I can disable this feature. i.e. delete the record but not update the sequence of the remaining records.

Thanks.

**Comment by highsolutions** [comment]
For now, there is no such option. Did this feature cause you a problem with model events on update?

**Comment by byanju** [comment]
Yes, I am actually trying to use this package in an accounting system. I want to assign sequence number generated by this package to a voucher. Thus once assigned sequence number i.e. code for a voucher should be constant for the voucher. It should not be changed in any case since the voucher will be addressed by its voucher code therein after.

**Comment by highsolutions** [comment]
Hello @byanju - release 2.6.2 has new config parameter - "NotUpdateOnDelete" which solves your problem. Cheers ;).

**Comment by byanju** [comment]
Cheers mate!!
