### ISSUE TITLE
Redundant queries in moveFurther and moveEarlier functions of SequenceService

### ISSUE THREAD

**Issue by osukono** [highsolutions/eloquent-sequence#14]
We can improve performance by massively decrement and increment sequence fields

`$query->where($this->getSequenceConfig('fieldName'), '>', $currentSequence)
            ->where($this->getSequenceConfig('fieldName'), '<=', $position)
            ->decrement($this->getSequenceConfig('fieldName'));`

`$query->where($this->getSequenceConfig('fieldName'), '>=', $position)
            ->where($this->getSequenceConfig('fieldName'), '<', $currentSequence)
            ->increment($this->getSequenceConfig('fieldName'));`

**Comment by highsolutions** [comment]
Thank you @osukono !

We've implemented it and released: https://github.com/highsolutions/eloquent-sequence/releases/tag/3.0.2
