### ISSUE TITLE
Not working with Event::fake()

### ISSUE THREAD

**Issue by jcwirko** [highsolutions/eloquent-sequence#15]
I have a test that works well, but I need to test the events, then I add 

` Event::fake()`;

`  ... code `

 `Event::assertDispatched(WorkOrderCreatedEvent::class);`

With Event Fake, I receive an error

> Not null violation: 7 ERROR:  null value in column "id_seq" violates not-null constraint

**Comment by highsolutions** [comment]
Hello @jcwirko . Did you tried to fake only this one event?

`Event::fake([WorkOrderCreatedEvent::class]);``

Whole package is built upon events, so it's impossible to fake all of them and to work properly.
