### ISSUE TITLE
Change group

### ISSUE THREAD

**Issue by Julien1138** [highsolutions/eloquent-sequence#16]
Hi,

I'm very happy with using this package. Thanks a lot !
Today I'm facing a situation where I need to move an object from one group to an other. It seems that there is no easy way to do this wright now. Any idea how I could do that ? (without using Section::refreshSequence() which seems a little heavy on a large database)

Are you maybe planning on implementing such a fonctionnality ?

**Comment by highsolutions** [comment]
Hello @Julien1138 . We're happy that you like our package ;).

We've never had a need for changing a group for the object, but I can imagine now the cases where this can be useful. I think that we will prepare something like that in future, but I cannot promise anything soon.

**Comment by highsolutions** [comment]
Thank you @Julien1138 for PR! And sorry it took us so long to integrate your solution to the package.
