### ISSUE TITLE
Refresh sequence doesn't start at 0

### ISSUE THREAD

**Issue by TheDevRay** [highsolutions/eloquent-sequence#25]
When calling the `Section::refreshSequence();` just like documented, the sequence refreshes, but it starts at 1 rather than 0.

As stated in the [read me - configuration](https://github.com/highsolutions/eloquent-sequence#configuration) you have to explicitly set the `orderFrom1` to `true`, defaulting to `false`. Either way using the default option or literally setting the option, the `refreshSequence` method starts storing the sequence from 1.

It is not the biggest issue in the world, but it makes for inconsistent data.

**Comment by adammatysiak** [comment]
Hi @TheDevRay,
very sorry for such a late answer. 

The `orderFrom1` method concerns only `move` method and your front-end, not if the `seq` starts from 0 or 1. Currently, it always starts from 1.
