### ISSUE TITLE
Support for laravel 7.4

### ISSUE THREAD

**Issue by touilahmedimad** [highsolutions/eloquent-sequence#28]
Hi, i tried to require the package for laravel version 7.4 , and here it is the output of the console 

> - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].

**Comment by highsolutions** [comment]
Hi @touilahmedimad , seconds ago we released a new version of the package - 3.7.0 with the support for Laravel 7. Sorry for keeping you waiting.
