### ISSUE TITLE
`up()` behaviour incorrect

### ISSUE THREAD

**Issue by vaughany** [highsolutions/eloquent-sequence#3]
I have a fresh install of Laravel 5.5.28 and used composer to install `eloquent-sequence` 1.2.2.  I have a basic post model which is seeded with sample data.  When I use `$post->up();` to move the sequence up by one, it instead moves to the top.

I have the following defined on a Post model:

```
use Sequence;
public function sequence() {
    return [ 'fieldName' => 'seq' ];
}
```
Using `tinker` I initially queried the database:
```
>>> App\Post::orderBy('seq', 'asc')->get();
=> Illuminate\Database\Eloquent\Collection {#756
     all: [
       App\Post {#757
         id: 1,
         title: "English 1",
         seq: 1,
       },
       App\Post {#758
         id: 2,
         title: "English 2",
         seq: 2,
       },
       App\Post {#759
         id: 3,
         title: "Maths 1",
         seq: 3,
       },
       App\Post {#760
         id: 4,
         title: "Maths 2",
         seq: 4,
       },
     ],
   }
```
I retrieved the last result (with the name 'Maths 2'):
```
>>> $p = App\Post::find(4);
=> App\Post {#747
     id: 4,
     title: "Maths 2",
     seq: 4,
   }
```
I moved it up:
```
>>> $p->up()
=> App\Post {#747
     id: 4,
     title: "Maths 2",
     seq: 1,
   }
```
Note that the `seq` field has gone from 4 to 1, not 3 as expected.

Whole-database query, showing that Maths 2 has not moved to position 3 as expected, and has swapped places with `seq` 1:
```
>>> App\Post::orderBy('seq', 'asc')->get();
=> Illuminate\Database\Eloquent\Collection {#755
     all: [
       App\Post {#763
         id: 4,
         title: "Maths 2",
         seq: 1,
       },
       App\Post {#765
         id: 2,
         title: "English 2",
         seq: 2,
       },
       App\Post {#749
         id: 3,
         title: "Maths 1",
         seq: 3,
       },
       App\Post {#731
         id: 1,
         title: "English 1",
         seq: 4,
       },
     ],
   }

```
The `down` method seems to work as expected: 
```
>>> $p->down()
=> App\Post {#758
     id: 4,
     title: "Maths 2",
     seq: 2,
   }
```

**Comment by highsolutions** [comment]
Thank you @vaughany for posting this issue.

We've added full test suite for the package and fixed this bug.

Please update our package to version 2.0.0.

**Comment by vaughany** [comment]
Thank you. I've run the tests and they all pass.  Unfortunately, I'm now I'm seeing issues with `down()`.

I've edited `composer.json` and run `composer update`. Starting from a freshly seeded database as per my example above:
```
>>> $p = App\Post::find(4);
=> App\Post {#746
     id: 4,
     title: "Maths 2",
     seq: 4,
   }
```
Up now works as expected, but down now moves the item directly to the end, instead of down one:
```
>>> $p->up()
=> App\Post {#746
     id: 4,
     title: "Maths 2",
     seq: 3,
   }
>>> $p->up()
=> App\Post {#746
     id: 4,
     title: "Maths 2",
     seq: 2,
   }
>>> $p->down()
=> App\Post {#746
     id: 4,
     title: "Maths 2",
     seq: 4,
   }
```

**Comment by highsolutions** [comment]
Sorry about that. We didn't cover this situation in our unit tests.

We've issued releases with fix for this bug (1.3.1 and 2.0.1).

We hope that now everything is okay ;).

**Comment by vaughany** [comment]
Perfect, thank you for your speedy solution. :)

**Comment by vaughany** [comment]
For what it's worth, I'm running phpunit from the root folder of my project, and it's only running two tests with two assertions (but I appreciate I may be doing this wrong!):
```
$ vendor/bin/phpunit 
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.
..                                                                  2 / 2 (100%)
Time: 127 ms, Memory: 12.00MB
OK (2 tests, 2 assertions)
```

**Comment by highsolutions** [comment]
When you clone repo to separate folder and run there tests (via `vendor/bin/phpunit`) than you will execute  all tests for package. When you are executing `phpunit` inside Laravel's project repo, then you execute default Laravel's test suite.
