### ISSUE TITLE
Support Laravel 5.6

### ISSUE THREAD

**Issue by vaughany** [highsolutions/eloquent-sequence#6]
Hi there. It would be great if this package could be updated to support Laravel 5.6.  I'm not sure what that would entail or I'd submit a PR myself.

**Comment by highsolutions** [comment]
Hi @vaughany . We plan to add support for Laravel 5.6 this week. I'll let you know when we finish it.

**Comment by highsolutions** [comment]
Hi @vaughany . We've prepared releases and branches for each version of Laravel since 5.1.

Release 2.6.0 supports Laravel 5.6 now. https://github.com/highsolutions/eloquent-sequence/releases/tag/2.6.0
